version: '3.7'
services:
  app:
    build:
      target: dev
      context: .
    container_name: rails-demo-app
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: postgres:11